import React, { useEffect, useState } from 'react';
import {
    Box,
    Typography,
    Card,
    CardContent,
    CircularProgress,
    Stack,
    Chip,
    Snackbar,
    Alert,
    Button,
    Divider,
    Grid,
    Paper,
    TextField,
    InputAdornment,
    Dialog,
    DialogTitle,
    DialogContent,
    DialogContentText,
    DialogActions,
} from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import RestaurantIcon from '@mui/icons-material/Restaurant';
import SearchIcon from '@mui/icons-material/Search';
import DeleteIcon from '@mui/icons-material/Delete';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const AiSavedRecipesPage = () => {
    const navigate = useNavigate();

    const [recipes, setRecipes] = useState([]);
    const [filteredRecipes, setFilteredRecipes] = useState([]);
    const [loading, setLoading] = useState(true);
    const [snackbar, setSnackbar] = useState({
        open: false,
        message: '',
        severity: 'error',
    });
    const [search, setSearch] = useState('');

    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
    const [deleteRecipeId, setDeleteRecipeId] = useState(null);

    const token = localStorage.getItem('token');

    // Fetch saved recipes
    useEffect(() => {
        const fetchSavedRecipes = async () => {
            try {
                const { data } = await axios.get(
                    'http://localhost:5000/api/ai/recipes',
                    { headers: { Authorization: `Bearer ${token}` } }
                );
                setRecipes(data);
                setFilteredRecipes(data);
            } catch (error) {
                setSnackbar({
                    open: true,
                    message: 'Failed to load saved recipes',
                    severity: 'error',
                });
            } finally {
                setLoading(false);
            }
        };
        fetchSavedRecipes();
    }, []);

    // Filter recipes based on search
    useEffect(() => {
        if (!search.trim()) {
            setFilteredRecipes(recipes);
        } else {
            setFilteredRecipes(
                recipes.filter((r) =>
                    r.title.toLowerCase().includes(search.toLowerCase())
                )
            );
        }
    }, [search, recipes]);

    // Open confirmation dialog
    const confirmDelete = (id) => {
        setDeleteRecipeId(id);
        setDeleteDialogOpen(true);
    };

    // Delete a saved recipe
    const handleDelete = async () => {
        if (!deleteRecipeId) return;
        try {
            await axios.delete(`http://localhost:5000/api/ai/recipe/${deleteRecipeId}`, {
                headers: { Authorization: `Bearer ${token}` },
            });
            setRecipes((prev) => prev.filter((r) => r._id !== deleteRecipeId));
            setSnackbar({ open: true, message: 'Recipe deleted ✅', severity: 'success' });
        } catch (err) {
            setSnackbar({ open: true, message: 'Failed to delete recipe', severity: 'error' });
        } finally {
            setDeleteDialogOpen(false);
            setDeleteRecipeId(null);
        }
    };

    if (loading) {
        return (
            <Box display="flex" justifyContent="center" mt={8}>
                <CircularProgress />
            </Box>
        );
    }

    return (
        <Box maxWidth={1100} mx="auto" px={2} py={3}>
            {/* Back */}
            <Button
                startIcon={<ArrowBackIcon />}
                onClick={() => navigate(-1)}
                sx={{ mb: 2 }}
            >
                Back
            </Button>

            <Typography variant="h4" fontWeight="bold" mb={1}>
                Saved AI Recipes ❤️
            </Typography>
            <Typography color="text.secondary" mb={3}>
                Recipes generated by AI and saved by you
            </Typography>

            {/* Search */}
            <Box mb={3} display="flex" justifyContent="flex-start">
                <TextField
                    size="small"
                    placeholder="Search recipes..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    sx={{ width: 300 }}
                    InputProps={{
                        startAdornment: (
                            <InputAdornment position="start">
                                <SearchIcon color="action" />
                            </InputAdornment>
                        ),
                    }}
                />
            </Box>

            {/* Empty State */}
            {filteredRecipes.length === 0 && (
                <Card sx={{ p: 4, borderRadius: 3 }}>
                    <Typography align="center" color="text.secondary">
                        No recipes found 🤖🍽️
                    </Typography>
                </Card>
            )}

            {/* Recipe List */}
            <Grid container spacing={3}>
                {filteredRecipes.map((recipe) => (
                    <Grid item xs={12} md={6} key={recipe._id}>
                        <Card
                            sx={{
                                borderRadius: 4,
                                height: '100%',
                                boxShadow: '0 12px 30px rgba(0,0,0,0.08)',
                            }}
                        >
                            {/* Header */}
                            <Box
                                sx={{
                                    p: 2.5,
                                    background: 'linear-gradient(135deg, #673ab7, #512da8)',
                                    color: 'white',
                                    cursor: 'pointer',
                                }}
                                onClick={() =>
                                    navigate(`/generated-ai-recipes/${recipe._id}`)
                                }
                            >
                                <Typography fontWeight="bold">{recipe.title}</Typography>
                                <Typography variant="body2" mt={0.5}>
                                    {recipe.description}
                                </Typography>
                            </Box>

                            <CardContent>
                                {/* Meta */}
                                <Stack direction="row" spacing={1} mb={2} flexWrap="wrap">
                                    <Chip icon={<AccessTimeIcon />} label={`${recipe.cookingTime} mins`} />
                                    <Chip icon={<RestaurantIcon />} label={recipe.difficulty.toUpperCase()} />
                                    <Chip label={recipe.category} />
                                    <Chip label={recipe.cuisine} />
                                </Stack>

                                <Divider sx={{ my: 2 }} />

                                {/* Ingredients */}
                                <Typography fontWeight="bold" mb={1}>
                                    Ingredients
                                </Typography>
                                <Stack direction="row" spacing={1} flexWrap="wrap">
                                    {recipe.ingredients.slice(0, 6).map((ing, i) => (
                                        <Chip key={i} label={ing.name} variant="outlined" />
                                    ))}
                                    {recipe.ingredients.length > 6 && (
                                        <Chip label={`+${recipe.ingredients.length - 6} more`} />
                                    )}
                                </Stack>

                                {/* Steps preview */}
                                <Paper variant="outlined" sx={{ mt: 2, p: 2, borderRadius: 2 }}>
                                    <Typography variant="body2" color="text.secondary">
                                        {recipe.steps[0]?.instruction}
                                    </Typography>
                                </Paper>

                                {/* Delete Button */}
                                <Button
                                    variant="outlined"
                                    color="error"
                                    startIcon={<DeleteIcon />}
                                    sx={{ mt: 2 }}
                                    fullWidth
                                    onClick={() => confirmDelete(recipe._id)}
                                >
                                    Delete Recipe
                                </Button>
                            </CardContent>
                        </Card>
                    </Grid>
                ))}
            </Grid>

            {/* Delete Confirmation Dialog */}
            <Dialog
                open={deleteDialogOpen}
                onClose={() => setDeleteDialogOpen(false)}
            >
                <DialogTitle>Delete Recipe</DialogTitle>
                <DialogContent>
                    <DialogContentText>
                        Are you sure you want to delete this recipe? This action cannot be undone.
                    </DialogContentText>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDeleteDialogOpen(false)}>Cancel</Button>
                    <Button color="error" onClick={handleDelete}>
                        Delete
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Snackbar */}
            <Snackbar
                open={snackbar.open}
                autoHideDuration={3000}
                onClose={() => setSnackbar({ ...snackbar, open: false })}
            >
                <Alert severity={snackbar.severity} variant="filled">
                    {snackbar.message}
                </Alert>
            </Snackbar>
        </Box>
    );
};

export default AiSavedRecipesPage;
